import type { Metadata } from "next";
import "./globals.css";
import localfont from "@next/font/local";

const LTInstitute = localfont({
  src: "../fonts/LTInstitute.otf",
  variable: "--LTInstitute", //css変数名を定義する必要がある。
 });

export const metadata: Metadata = {
  title: " EarthQuake ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={LTInstitute.className}>{children}</body>
    </html>
  );
}
